id: A8D20080B
title: Brief Succession of Lives Prayer
type: translation
pechas:
- I634D693A
- I0EF4686F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:51:44.501644
  last_modified_at: 2023-01-04 12:51:44.501664
  collections:
  - Khenchen Ngawang Palzang Series
  - Works of Tibetan Masters
alignment_to_base:
  I634D693A/4876: D2FC
  I0EF4686F/1EA3: D2FC
